name = "bp-screener"
compatibility_date = "2026-07-09"
pages_build_output_dir = "web"

[[d1_databases]]
binding = "DB"
database_name = "bp-screener"
database_id = "b9b63d43-e359-4ee5-b4b2-d6b281688cc5"
