const labels = {
  en: {
    eyebrow: "Lightweight Deal Flow Screening",
    title: "Search, filter, and understand pitch decks faster.",
    subtitle:
      "A Cloudflare-ready frontend for structured BP profiles generated by the local Python ingestion pipeline.",
    keyword: "Keyword",
    industry: "Industry",
    stage: "Stage",
    recommendation: "Recommendation",
    any: "Any",
    high: "High",
    medium: "Medium",
    low: "Low",
    unknown: "Unknown",
    aiOnly: "AI-related only",
    search: "Search",
    projects: "Projects",
    aiProjects: "AI-related",
    sourceSearch: "Source Snippet Search",
    searchSnippets: "Search snippets",
    noProjects: "No projects found. Ingest BP files locally, then sync data to D1.",
    view: "View details",
    file: "File",
    stageLabel: "Stage",
    businessModel: "Business Model",
    team: "Team Highlights",
    traction: "Traction",
    risks: "Risks",
    evidence: "Evidence",
    page: "Page",
  },
  zh: {
    eyebrow: "轻量级项目筛选",
    title: "更快检索、筛选和理解 BP。",
    subtitle: "基于 Cloudflare 的网页前端，用于展示本地 Python 管道生成的结构化 BP 项目档案。",
    keyword: "关键词",
    industry: "行业",
    stage: "阶段",
    recommendation: "推荐等级",
    any: "不限",
    high: "高",
    medium: "中",
    low: "低",
    unknown: "未知",
    aiOnly: "只看 AI 相关",
    search: "搜索",
    projects: "项目",
    aiProjects: "AI 相关",
    sourceSearch: "原文片段搜索",
    searchSnippets: "搜索片段",
    noProjects: "还没有项目。请先在本地导入 BP，再把数据同步到 D1。",
    view: "查看详情",
    file: "文件",
    stageLabel: "阶段",
    businessModel: "商业模式",
    team: "团队亮点",
    traction: "当前进展",
    risks: "风险",
    evidence: "证据",
    page: "第",
  },
};

let lang = localStorage.getItem("bp-screener-lang") || "en";
let projects = [];

const language = document.querySelector("#language");
const grid = document.querySelector("#projectGrid");
const snippetList = document.querySelector("#snippetList");
const dialog = document.querySelector("#projectDialog");
const detail = document.querySelector("#projectDetail");

language.value = lang;
language.addEventListener("change", () => {
  lang = language.value;
  localStorage.setItem("bp-screener-lang", lang);
  applyLanguage();
  renderProjects(projects);
});

document.querySelector("#searchButton").addEventListener("click", loadProjects);
document.querySelector("#snippetButton").addEventListener("click", searchSnippets);
document.querySelector("#closeDialog").addEventListener("click", () => dialog.close());

applyLanguage();
loadProjects();

function t(key) {
  return labels[lang][key] || key;
}

function applyLanguage() {
  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    node.textContent = t(node.dataset.i18n);
  });
}

async function loadProjects() {
  const params = new URLSearchParams();
  setParam(params, "q", value("#keyword"));
  setParam(params, "industry", value("#industry"));
  setParam(params, "stage", value("#stage"));
  setParam(params, "recommendation", value("#recommendation"));
  if (document.querySelector("#aiOnly").checked) params.set("aiOnly", "true");

  const response = await fetch(`/api/projects?${params.toString()}`);
  const data = await response.json();
  projects = data.projects || [];
  renderProjects(projects);
}

async function searchSnippets() {
  const q = value("#keyword");
  if (!q) {
    snippetList.innerHTML = "";
    return;
  }
  const response = await fetch(`/api/search?q=${encodeURIComponent(q)}`);
  const data = await response.json();
  const snippets = data.snippets || [];
  snippetList.innerHTML = snippets
    .map(
      (item) => `
        <article class="snippet">
          <strong>${escapeHtml(item.file_name || "")}</strong>
          <p>${t("page")} ${item.page || t("unknown")}</p>
          <p>${escapeHtml(item.snippet || "")}</p>
        </article>
      `,
    )
    .join("");
}

function renderProjects(items) {
  document.querySelector("#projectCount").textContent = String(items.length);
  document.querySelector("#aiCount").textContent = String(items.filter((item) => item.ai_related).length);

  if (!items.length) {
    grid.innerHTML = `<div class="panel card">${t("noProjects")}</div>`;
    return;
  }

  grid.innerHTML = items.map(projectCard).join("");
  grid.querySelectorAll("[data-document-id]").forEach((button) => {
    button.addEventListener("click", () => showProject(button.dataset.documentId));
  });
}

function projectCard(project) {
  const tags = [
    project.industry,
    project.financing_stage,
    project.ai_related ? "AI" : "",
    ...(project.tags || []).slice(0, 3),
  ].filter(Boolean);

  return `
    <article class="card">
      <h3>${escapeHtml(project.project_name || project.company_name || t("unknown"))}</h3>
      <p class="summary">${escapeHtml(project.one_line_summary || "")}</p>
      <div class="tags">${tags.map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join("")}</div>
      <div class="meta">
        <span><strong>${t("stageLabel")}:</strong> ${escapeHtml(project.financing_stage || t("unknown"))}</span>
        <span><strong>${t("businessModel")}:</strong> ${escapeHtml(project.business_model || t("unknown"))}</span>
        <span><strong>${t("file")}:</strong> ${escapeHtml(project.file_name || "")}</span>
      </div>
      <button data-document-id="${project.document_id}">${t("view")}</button>
    </article>
  `;
}

async function showProject(documentId) {
  const response = await fetch(`/api/projects/${documentId}`);
  const data = await response.json();
  const project = data.project;
  if (!project) return;

  detail.innerHTML = `
    <h2>${escapeHtml(project.project_name || project.company_name || t("unknown"))}</h2>
    <p class="summary">${escapeHtml(project.one_line_summary || "")}</p>
    <div class="detailGrid">
      ${detailItem(t("industry"), project.industry)}
      ${detailItem("AI", project.ai_related ? "Yes" : "No")}
      ${detailItem(t("stageLabel"), project.financing_stage)}
      ${detailItem(t("businessModel"), project.business_model)}
      ${detailItem(t("team"), join(project.team_highlights))}
      ${detailItem(t("traction"), join(project.traction))}
      ${detailItem(t("risks"), join(project.risks))}
      ${detailItem(t("file"), project.file_name)}
    </div>
    ${
      project.evidence?.length
        ? `<h3>${t("evidence")}</h3><ul>${project.evidence
            .map((item) => `<li>${escapeHtml(item.quote || "")}</li>`)
            .join("")}</ul>`
        : ""
    }
  `;
  dialog.showModal();
}

function detailItem(label, value) {
  return `<div class="detailItem"><small>${escapeHtml(label)}</small>${escapeHtml(value || t("unknown"))}</div>`;
}

function join(value) {
  return Array.isArray(value) ? value.join(", ") : value || "";
}

function value(selector) {
  return document.querySelector(selector).value.trim();
}

function setParam(params, key, item) {
  if (item) params.set(key, item);
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
